# Generated by Django 4.0.4 on 2022-04-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadejte jméno předmětu', max_length=50, unique=True, verbose_name='Subject Name')),
                ('short', models.CharField(help_text='Zadejte jeho zkratku', max_length=5, unique=True, verbose_name='Subject Short')),
                ('desc', models.TextField(help_text='Popište předmět', verbose_name='Subject Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
