# Generated by Django 4.0.4 on 2022-04-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadejte jméno učitele', max_length=50, unique=True, verbose_name='Teacher Name')),
                ('titul', models.CharField(choices=[], help_text='Zadejte titul učitele', max_length=7, verbose_name="Teacher 's Title")),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(choices=[], help_text='Zadejte Název Učebny', max_length=10, verbose_name='Classroom Name')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.subjectinfo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='teachers',
            field=models.ManyToManyField(help_text='Zvolte učitele předmětu', to='guide.teacher'),
        ),
    ]
