# Generated by Django 4.0.4 on 2022-04-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_alter_teacher_titul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='classroom',
            field=models.CharField(help_text='Zadejte Název Učebny', max_length=10, verbose_name='Classroom Name'),
        ),
    ]
