# Generated by Django 4.0.4 on 2022-04-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_alter_teacher_titul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='titul',
            field=models.CharField(choices=[('Mgr.', 'Mgr.'), ('Ing.', 'Ing.'), ('RNDr.', 'RNDr.'), ('', '_')], default='_', help_text='Zadejte titul učitele', max_length=7, verbose_name="Teacher 's Title"),
        ),
    ]
