# Generated by Django 3.2.9 on 2022-06-05 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_alter_teacher_titul'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name__name']},
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text='Krátce popište, co je cílem kódu', max_length=100, verbose_name='Obsah kódu')),
                ('codedesc', models.TextField(help_text='Stručně popište, jak bude kód fungovat', verbose_name='Popis kódu')),
                ('difficulty', models.IntegerField(blank=True, help_text='Zadejte obtížnost kódu v hodnotách od 1 do 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Obtížnost kódu (1-10)')),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.subjectinfo')),
            ],
            options={
                'ordering': ['codename'],
            },
        ),
    ]
