# Generated by Django 3.2.9 on 2022-06-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_auto_20220605_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Název jazyka', max_length=100, verbose_name='Název jazyka')),
                ('desc', models.TextField(help_text='Stručně popište, jak bude kód fungovat', verbose_name='Popis kódu')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='code',
            old_name='codedesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='codename',
            new_name='name',
        ),
        migrations.AddField(
            model_name='code',
            name='lang',
            field=models.ManyToManyField(help_text='Vyberte název jazyka', to='guide.Lang'),
        ),
    ]
