# Generated by Django 3.2.9 on 2022-06-21 19:10

import django.core.validators
from django.db import migrations, models
import guide.models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0012_auto_20220611_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Krátce popište, co je cílem kódu', max_length=100, verbose_name='Obsah kódu')),
                ('desc', models.TextField(help_text='Stručně popište, jak bude kód fungovat', verbose_name='Popis kódu')),
                ('difficulty', models.IntegerField(blank=True, help_text='Zadejte obtížnost kódu v hodnotách od 1 do 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Obtížnost kódu (1-10)')),
                ('sit', models.FileField(null=True, upload_to=guide.models.sit_path, verbose_name='Zdrojový kód')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
