# Generated by Django 3.2.9 on 2022-06-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0013_sit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sit',
            name='shortdesc',
            field=models.TextField(default='yes', help_text='Stručně popište, jak bude kód fungovat', verbose_name='Stručný popis kódu'),
            preserve_default=False,
        ),
    ]
